h_min: 103                  # Minimum value of hue.
s_min: 10                   # Minimum value of saturation.
v_min: 10                   # Minimum value of value.
h_max: 157                  # Maximum value of hue.
s_max: 240                  # Maximum value of saturation.
v_max: 240                  # Maximum value of value.
canny_lower: 100            # Lower bound for canny edge.
canny_upper: 200            # Upper bound for canny edge.
canny_ker: 3                # Size of the kernel used for Canny edge detection,
min_contour_area: 300       # Minimum area of the contour, used for filtering.
std_dev_bound: 0.465        # Upper bound for the standard deviation of the distances between points on the contour and and the centre. 
                            # It's used to determine whether a contour can be said a circle or not.
verbose: true               # Used for debugging purposes.
