h_min: 103                  # Minimum value of hue.
s_min: 10                   # Minimum value of saturation.
v_min: 10                   # Minimum value of value.
h_max: 157                  # Maximum value of hue.
s_max: 240                  # Maximum value of saturation.
v_max: 240                  # Maximum value of value.
canny_lower: 100            # Lower bound for canny edge.
canny_upper: 200            # Upper bound for canny edge.
canny_ker: 3                # Size of the kernel used for Canny edge detection,
dock_radius: 2              # Radius of the docks.
inter_centre_dist: 6        # Distance between the centre of one of outer circles and that of the inner circle.
min_contour_area: 1200      # Minimum area of the contour, used for filtering.
verbose: true               # Used for debugging purposes.
